(require 'package)
(setq package-enable-at-startup nil)

(setq package-archives '(("gnu" . "https://mirrors.ustc.edu.cn/elpa/gnu/")
                         ("melpa" . "https://mirrors.ustc.edu.cn/elpa/melpa/")
                         ("nongnu" . "https://mirrors.ustc.edu.cn/elpa/nongnu/")))


(package-initialize)

(defun use-package (package)
  (unless (package-installed-p package)
    (package-refresh-contents)
    (package-install package))
  (package-installed-p package))


;(use-package  'mood-line)
(use-package 'kaolin-themes)
;(use-package 'moody)
(use-package 'helm)
;(use-package 'simple-modeline)
(use-package 'all-the-icons)
;(use-package 'nerd-icons)
(use-package 'centaur-tabs)
(use-package 'company)
(use-package 'company-box)
(use-package 'dash)
(use-package 'dashboard)
;(use-package 'eat)
;(use-package 'epl)
(use-package 'flycheck)
(use-package 'frame-local)
(use-package 'leuven-theme)
(use-package 'macrostep)
(use-package 'neotree)
(use-package 'org-bullets)
(use-package 'pkg-info)
;(use-package 'powerline)
(use-package 'projectile)
(use-package 'rich-minority)
(use-package 'slime)
;(use-package 'smart-mode-line)
(use-package 'zenburn-theme)
(use-package 'dirvish)
(use-package 'kaolin-themes)
;;nano
;(use-package 'nano-theme)

;;LSP
;(use-package 'lsp-mode)
;l(use-package 'lsp-ui)
(use-package 'yasnippet)
;(use-package 'lsp-java)
					;(use-package 'lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration)))
;(use-package 'hydra)
;(use-package company)
;(use-package lsp-ui)
;(use-package 'which-key :config (which-key-mode))
;(use-package 'lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package 'gradle-mode)
(provide 'init-package)
